# Generated by Django 3.1.5 on 2021-04-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210119_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='asphalt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='concrete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='cruising',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='indoor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='ramps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='skateType',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='location',
            name='wood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='asphalt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='concrete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='cruising',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='indoor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='ramps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='skateType',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='member',
            name='wood',
            field=models.IntegerField(default=0),
        ),
    ]
